name: 🐛 Bug Report
description: Report a bug or issue with PSA Grading App
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees:
  - lead-developer

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the following information to help us resolve the issue quickly.
        
        **⚠️ Security Issues**: If this is a security vulnerability, please **DO NOT** create a public issue. Instead, report it privately via our [Security Policy](../SECURITY.md).

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-Report Checklist
      description: Please verify these steps before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have tried the latest version of the application
          required: true
        - label: This is not a security vulnerability (use Security Policy instead)
          required: true

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Category
      description: What type of bug is this?
      options:
        - UI/UX Issue
        - PSA Integration Problem  
        - File Upload Issue
        - Email/Notification Problem
        - Database/Data Issue
        - Authentication Problem
        - Performance Issue
        - Mobile/Responsive Issue
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this bug?
      options:
        - Low - Minor inconvenience
        - Medium - Affects functionality
        - High - Major feature broken
        - Critical - App unusable/data loss
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "The PSA search function returns incorrect results when..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to PSA search page
        2. Enter card name "Charizard"
        3. Click search button
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "The search should return a list of Charizard cards with images and details"
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "The search returns 'No cards found' or shows incorrect cards"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where did you encounter this bug?
      options:
        - Production (live website)
        - Staging/Testing environment
        - Local development
        - Review/Preview deployment
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Chrome
        - Mobile Safari
        - Other (specify in additional context)

  - type: dropdown
    id: device
    attributes:
      label: Device Type
      description: What device are you using?
      options:
        - Desktop/Laptop
        - Mobile Phone
        - Tablet
        - Other

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser? (e.g., Chrome 119.0.6045.105)
      placeholder: "Chrome 119.0.6045.105"

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: "Windows 11, macOS 13, iOS 17, Android 13, etc."

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: Any error messages you see (console errors, alert messages, etc.)
      placeholder: |
        Console errors:
        Error: Cannot read property 'name' of undefined
        
        User-facing errors:
        "Something went wrong. Please try again."
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem. You can drag and drop images here.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here. For example:
        - Does this happen consistently or intermittently?
        - Did this work before? When did it stop working?
        - Any workarounds you found?
        - Network conditions (slow internet, etc.)

  - type: checkboxes
    id: technical-details
    attributes:
      label: Technical Information (if applicable)
      description: Check any that apply to help our technical team
      options:
        - label: This affects the PSA integration specifically
        - label: This affects file uploads (cards/videos)  
        - label: This affects the Shopify integration
        - label: This affects email notifications
        - label: This affects admin dashboard
        - label: This affects mobile responsive design
        - label: This seems related to database/performance

  - type: textarea
    id: impact
    attributes:
      label: Business Impact
      description: How does this bug affect users or the business?
      placeholder: |
        - Users cannot submit grading requests
        - 50% of searches return wrong results  
        - Admin cannot process videos
        - Email notifications not sent

  - type: input
    id: contact
    attributes:
      label: Contact Information (Optional)
      description: If you want to be contacted for follow-up questions
      placeholder: "your-email@example.com or @your-github-handle"

  - type: markdown
    attributes:
      value: |
        ---
        
        ### What Happens Next?
        
        1. **Triage** - Our team will review and label your issue within 24 hours
        2. **Investigation** - We'll reproduce the issue and investigate the cause
        3. **Fix** - We'll develop and test a fix
        4. **Deploy** - The fix will be deployed and you'll be notified
        
        Thank you for helping improve PSA Grading App! 🚀